name: translate
description: A google translate project.


publish_to: 'none'
version: 1.0.0+1

# Environment
environment:
  sdk: ">=2.12.0 <3.0.0"
# ---

# Dependencies
dependencies:

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.9
  http: ^0.13.4
  translator: ^0.1.7

# ---

# Dev dependencies
dev_dependencies:

  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

# ---

# Flutter
flutter:
  uses-material-design: true

# ---